/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../services/usuarioService`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup/page` | `/signup/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(panel)'}/profile/add` | `/profile/add`; params?: Router.UnknownInputParams; } | { pathname: `${'/(panel)'}/profile/addMedicine` | `/profile/addMedicine`; params?: Router.UnknownInputParams; } | { pathname: `${'/(panel)'}/profile/editProfile` | `/profile/editProfile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(panel)'}/profile/history` | `/profile/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(panel)'}/profile/home` | `/profile/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(panel)'}/profile/myMedicine` | `/profile/myMedicine`; params?: Router.UnknownInputParams; } | { pathname: `${'/(panel)'}/profile/profile` | `/profile/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(panel)'}/profile/tips` | `/profile/tips`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../services/usuarioService`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup/page` | `/signup/page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(panel)'}/profile/add` | `/profile/add`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(panel)'}/profile/addMedicine` | `/profile/addMedicine`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(panel)'}/profile/editProfile` | `/profile/editProfile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(panel)'}/profile/history` | `/profile/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(panel)'}/profile/home` | `/profile/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(panel)'}/profile/myMedicine` | `/profile/myMedicine`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(panel)'}/profile/profile` | `/profile/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(panel)'}/profile/tips` | `/profile/tips`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../services/usuarioService${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup/page${`?${string}` | `#${string}` | ''}` | `/signup/page${`?${string}` | `#${string}` | ''}` | `${'/(panel)'}/profile/add${`?${string}` | `#${string}` | ''}` | `/profile/add${`?${string}` | `#${string}` | ''}` | `${'/(panel)'}/profile/addMedicine${`?${string}` | `#${string}` | ''}` | `/profile/addMedicine${`?${string}` | `#${string}` | ''}` | `${'/(panel)'}/profile/editProfile${`?${string}` | `#${string}` | ''}` | `/profile/editProfile${`?${string}` | `#${string}` | ''}` | `${'/(panel)'}/profile/history${`?${string}` | `#${string}` | ''}` | `/profile/history${`?${string}` | `#${string}` | ''}` | `${'/(panel)'}/profile/home${`?${string}` | `#${string}` | ''}` | `/profile/home${`?${string}` | `#${string}` | ''}` | `${'/(panel)'}/profile/myMedicine${`?${string}` | `#${string}` | ''}` | `/profile/myMedicine${`?${string}` | `#${string}` | ''}` | `${'/(panel)'}/profile/profile${`?${string}` | `#${string}` | ''}` | `/profile/profile${`?${string}` | `#${string}` | ''}` | `${'/(panel)'}/profile/tips${`?${string}` | `#${string}` | ''}` | `/profile/tips${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../services/usuarioService`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup/page` | `/signup/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(panel)'}/profile/add` | `/profile/add`; params?: Router.UnknownInputParams; } | { pathname: `${'/(panel)'}/profile/addMedicine` | `/profile/addMedicine`; params?: Router.UnknownInputParams; } | { pathname: `${'/(panel)'}/profile/editProfile` | `/profile/editProfile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(panel)'}/profile/history` | `/profile/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(panel)'}/profile/home` | `/profile/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(panel)'}/profile/myMedicine` | `/profile/myMedicine`; params?: Router.UnknownInputParams; } | { pathname: `${'/(panel)'}/profile/profile` | `/profile/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(panel)'}/profile/tips` | `/profile/tips`; params?: Router.UnknownInputParams; };
    }
  }
}
